#!/bin/bash

# WTT Web - 一键部署完成报告

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 GitHub 推送成功！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 仓库地址: https://github.com/cecwxf/wtt-web"
echo "✅ 分支: main"
echo "✅ 提交数: 3"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 下一步: Vercel 部署（2 分钟完成）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "方法 1: 网页部署（推荐，最简单）"
echo ""
echo "1. 访问 Vercel 部署页面:"
echo "   https://vercel.com/new/clone?repository-url=https://github.com/cecwxf/wtt-web"
echo ""
echo "2. 点击 'Import' 按钮"
echo ""
echo "3. 配置环境变量（点击 'Environment Variables'）:"
echo "   变量名: NEXT_PUBLIC_WTT_API_URL"
echo "   值: http://170.106.109.4:8000"
echo ""
echo "4. 点击 'Deploy' 按钮"
echo ""
echo "5. 等待 1-2 分钟，部署完成！"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "方法 2: 从 Vercel Dashboard 导入"
echo ""
echo "1. 访问: https://vercel.com/new"
echo ""
echo "2. 选择 'Import Git Repository'"
echo ""
echo "3. 找到并选择 'cecwxf/wtt-web'"
echo ""
echo "4. 配置环境变量:"
echo "   NEXT_PUBLIC_WTT_API_URL=http://170.106.109.4:8000"
echo ""
echo "5. 点击 'Deploy'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 部署后配置"
echo ""
echo "部署成功后，你会得到一个 URL，如:"
echo "https://wtt-web-xxx.vercel.app"
echo ""
echo "需要更新后端 CORS 配置:"
echo ""
echo "1. 编辑 wtt_service/main.py"
echo "2. 在 allow_origins 中添加你的 Vercel URL"
echo "3. 运行 ./deploy.sh 重新部署后端"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 快速链接"
echo ""
echo "GitHub 仓库: https://github.com/cecwxf/wtt-web"
echo "Vercel 部署: https://vercel.com/new/clone?repository-url=https://github.com/cecwxf/wtt-web"
echo "Vercel Dashboard: https://vercel.com/dashboard"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 详细文档"
echo ""
echo "- VERCEL_DEPLOYMENT.md - 详细部署指南"
echo "- VERCEL_QUICKSTART.md - 快速参考"
echo "- VERCEL_READY.md - 部署说明"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 现在就开始部署吧！"
echo ""
echo "点击这个链接直接开始:"
echo "https://vercel.com/new/clone?repository-url=https://github.com/cecwxf/wtt-web"
echo ""

# 在浏览器中打开（如果可能）
if command -v xdg-open &> /dev/null; then
    read -p "是否在浏览器中打开 Vercel 部署页面? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        xdg-open "https://vercel.com/new/clone?repository-url=https://github.com/cecwxf/wtt-web"
    fi
fi
