export const mobileChatMessages = {
  zh: {
    'mobile.chooseHost': '选择主机',
    'mobile.chooseAgent': '选择 Agent',
    'mobile.chooseTopic': '选择 Topic',
    'mobile.chooseTarget': '选择主机 / Agent / Topic',
    'mobile.searchHosts': '搜索主机或 Agent',
    'mobile.searchAgents': '搜索当前主机下的 Agent',
    'mobile.searchTopics': '搜索当前 Agent 的 Topic',
    'mobile.newChat': '新建对话',
    'mobile.settings': '设置',
    'mobile.offline': '当前网络离线，草稿和附件会保留，恢复后可继续发送。',
    'mobile.directoryUnavailable': '目录暂时无法更新，当前对话已保留。',
    'mobile.reloadDirectory': '重新加载目录',
    'mobile.group': '群聊',
    'mobile.noAgent': '暂无 Agent',
    'mobile.manageAgents': '请在完整 Web Feed 中管理 Agent。',
    'mobile.fullWeb': '打开完整 Web Feed',
    'mobile.newChatTitle': '开始新对话',
    'mobile.newChatDescription': '创建普通任务对话或选择已有 Topic。',
    'mobile.createChat': '创建普通对话',
    'mobile.startChat': '开始对话',
    'mobile.firstMessage': '发送第一条消息',
    'mobile.sendFailed': '发送失败',
    'mobile.retry': '重试',
    'mobile.dismissFailure': '关闭发送失败提示',
    'mobile.originalImage': '查看原图 {name}',
    'mobile.uploading': '正在上传 {progress}%',
    'mobile.uploadFailed': '上传失败：{error}',
    'mobile.attach': '添加附件',
    'mobile.files': '文件/图片',
    'mobile.camera': '拍照',
    'mobile.location': '发送位置',
    'mobile.sendGroup': '发送到群聊...',
    'mobile.sendTask': '给 Agent 发送任务...',
    'mobile.message': '发送消息...',
    'mobile.send': '发送消息',
    'mobile.imagePreview': '图片预览',
    'mobile.closePreview': '关闭图片预览',
    'mobile.noAgents': '暂无 Agent，请先在完整 Web Feed 绑定或创建 Agent。',
    'mobile.hostAgents': '{online} 在线 · {count} 个 Agent',
    'mobile.backHosts': '返回主机',
    'mobile.noMatchingAgent': '当前主机下没有匹配的 Agent。',
    'mobile.backAgents': '返回 Agent',
    'mobile.noSelectedAgent': '未选择 Agent',
    'mobile.unknownHost': '未上报主机',
    'mobile.noRecent': '暂无最近对话',
    'mobile.noTopics': '暂无{kind}',
    'mobile.network': '网络 {state} · WebSocket {socket}',
    'mobile.online': '在线',
    'mobile.offlineState': '离线',
    'mobile.mobileSettings': '移动端设置页',
    'mobile.signOut': '退出登录',
    'mobile.close': '关闭',
    'mobile.members': '{count} 成员',
    'mobile.p2p': 'P2P 私聊',
    'mobile.tasks': '任务 Topic',
    'mobile.groups': '群聊 / 讨论',
    'mobile.broadcasts': '订阅 / 广播',
    'mobile.task': '任务',
    'mobile.broadcast': '订阅',
    'mobile.team': '协作群聊',
    'mobile.replied': 'Agent 已回复',
    'mobile.waitStatus': '等待 Agent 状态更新',
    'mobile.statusUpdate': 'Agent 状态更新',
    'mobile.queued': '消息已发送，等待 Agent 接收',
    'mobile.accepted': '消息已投递，等待 Agent 执行',
    'mobile.createFailed': '创建任务失败',
    'mobile.networkFailed': '网络异常，请稍后重试',
    'mobile.loginUpload': '请先登录后再上传附件',
    'mobile.fileTooLarge': '文件过大，最大 100MB，当前 {size}MB',
    'mobile.uploadError': '上传失败',
    'mobile.noLocation': '当前设备不支持定位',
    'mobile.locationFailed': '定位失败：{error}',
    'mobile.allMembers': '所有成员',
  },
  en: {
    'mobile.chooseHost': 'Choose host',
    'mobile.chooseAgent': 'Choose Agent',
    'mobile.chooseTopic': 'Choose Topic',
    'mobile.chooseTarget': 'Choose host, Agent or Topic',
    'mobile.searchHosts': 'Search hosts or Agents',
    'mobile.searchAgents': 'Search Agents on this host',
    'mobile.searchTopics': 'Search this Agent\'s Topics',
    'mobile.newChat': 'New conversation',
    'mobile.settings': 'Settings',
    'mobile.offline': 'You are offline. Your draft and attachments are saved until you reconnect.',
    'mobile.directoryUnavailable': 'The directory is unavailable. Your current conversation is preserved.',
    'mobile.reloadDirectory': 'Reload directory',
    'mobile.group': 'Group',
    'mobile.noAgent': 'No Agents',
    'mobile.manageAgents': 'Manage your Agents in the full Web Feed.',
    'mobile.fullWeb': 'Open full Web Feed',
    'mobile.newChatTitle': 'Start a conversation',
    'mobile.newChatDescription': 'Create a task conversation or choose an existing Topic.',
    'mobile.createChat': 'Create conversation',
    'mobile.startChat': 'Start chatting',
    'mobile.firstMessage': 'Send your first message',
    'mobile.sendFailed': 'Message failed',
    'mobile.retry': 'Retry',
    'mobile.dismissFailure': 'Dismiss sending error',
    'mobile.originalImage': 'Open original image {name}',
    'mobile.uploading': 'Uploading {progress}%',
    'mobile.uploadFailed': 'Upload failed: {error}',
    'mobile.attach': 'Add attachment',
    'mobile.files': 'Files / images',
    'mobile.camera': 'Take photo',
    'mobile.location': 'Send location',
    'mobile.sendGroup': 'Message the group...',
    'mobile.sendTask': 'Send a task to your Agent...',
    'mobile.message': 'Message...',
    'mobile.send': 'Send message',
    'mobile.imagePreview': 'Image preview',
    'mobile.closePreview': 'Close image preview',
    'mobile.noAgents': 'No Agents yet. Bind or create an Agent in the full Web Feed.',
    'mobile.hostAgents': '{online} online · {count} Agents',
    'mobile.backHosts': 'Back to hosts',
    'mobile.noMatchingAgent': 'No matching Agents on this host.',
    'mobile.backAgents': 'Back to Agents',
    'mobile.noSelectedAgent': 'No Agent selected',
    'mobile.unknownHost': 'Host not reported',
    'mobile.noRecent': 'No recent conversations',
    'mobile.noTopics': 'No {kind}',
    'mobile.network': 'Network {state} · WebSocket {socket}',
    'mobile.online': 'online',
    'mobile.offlineState': 'offline',
    'mobile.mobileSettings': 'Mobile settings',
    'mobile.signOut': 'Sign out',
    'mobile.close': 'Close',
    'mobile.members': '{count} members',
    'mobile.p2p': 'Direct messages',
    'mobile.tasks': 'Task Topics',
    'mobile.groups': 'Groups / discussions',
    'mobile.broadcasts': 'Subscriptions / broadcasts',
    'mobile.task': 'Task',
    'mobile.broadcast': 'Subscription',
    'mobile.team': 'Team',
    'mobile.replied': 'Agent replied',
    'mobile.waitStatus': 'Waiting for Agent status',
    'mobile.statusUpdate': 'Agent status updated',
    'mobile.queued': 'Message sent, waiting for Agent',
    'mobile.accepted': 'Message delivered, waiting for execution',
    'mobile.createFailed': 'Could not create task',
    'mobile.networkFailed': 'Network error. Please try again.',
    'mobile.loginUpload': 'Sign in before uploading attachments',
    'mobile.fileTooLarge': 'File exceeds 100MB limit ({size}MB)',
    'mobile.uploadError': 'Upload failed',
    'mobile.noLocation': 'Location is unavailable on this device',
    'mobile.locationFailed': 'Location failed: {error}',
    'mobile.allMembers': 'All members',
  },
}

export const mobileCommandDescriptions: Record<string, string> = {
  '/new task': 'Create task',
  '/new code task': 'Create coding task',
  '/new research task': 'Create research task',
  '/new topic': 'Create Topic',
  '/run': 'Run current task',
  '/workers': 'Agent workers',
  '/status': 'Execution status',
  '/help': 'Help',
  '/model': 'View or change model',
  '/compact': 'Compact context',
  '/clear': 'Clear session view',
  '/new': 'New runtime session',
  '/review': 'Review changes',
  '/init': 'Initialize project context',
  '/approvals': 'Approval policy',
  '/permissions': 'Permissions',
  '/diff': 'Current diff',
  '/mcp': 'MCP tools',
  '/agents': 'Manage subagents',
  '/config': 'Runtime configuration',
  '/memory': 'View or manage memory',
  '/cost': 'Usage and cost',
  '/tools': 'Available tools',
  '/stats': 'Session statistics',
  '/resume': 'Resume session',
  '/exit': 'Exit or disconnect runtime',
}
